name: On Push

on: [push]

jobs:
  build:
    strategy:
      matrix:
        # Supported platforms: https://docs.github.com/en/actions/reference/runners/github-hosted-runners
        os: [windows-latest, windows-11-arm, ubuntu-24.04-arm, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - if: ${{ runner.os != 'Windows' }}
        run: sudo sh ./Configure.${{ runner.os }}.Application.sh
      - run: dotnet build
  test:
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm, ubuntu-24.04-arm, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - if: ${{ runner.os != 'Windows' }}
        run: sudo sh ./Configure.${{ runner.os }}.Application.sh
      - run: dotnet test Nu/Nu.Tests
